name: Build & Upload to TestFlight

on:
  workflow_dispatch:

jobs:
  build-and-upload:
    name: Build & Upload
    runs-on: macos-latest

    steps:
      - name: Decode P12
        run: echo "${{ secrets.P12_BASE64 }}" | base64 --decode > distribution.p12
