name: Build & Upload to TestFlight

on:
  workflow_dispatch:

jobs:
  build-and-upload:
    name: Build & Upload
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "${{ secrets.P12_BASE64 }}"
